
default: &default
  adapter: postgresql  
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_microverse_final_capstone_development

test:
  <<: *default
  database: backend_microverse_final_capstone_test

production:
  <<: *default
  database: mysite_production
  url: <%= ENV['DATABASE_URL'] %>
  username: mysite
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>